### PR TITLE
Fixing ZDCChat/ZDCChat.h not found, by adding FRAMEWORK_SEARCH_PATHS.…

### PR DESCRIPTION
**Pull request by Frexuz**
… taskrabbit/react-native-zendesk-chat#21

### CODE REVIEW

**Comment by mjmaix** [comment]
@taskrabbit

Let me know if there are other things that needs to be done for this to be merged

**Comment by Fawxy** [comment]
Please merge this :)

**Comment by kg-currenxie** [comment]
lol, 1 year later...

**Comment by Rushi271193** [comment]
Hey I have tried adding the framework paths and yet I get this error. Tried making changes in project.pbxproj of my RNZendesk library yet i get the same error. Any other thing that i need to add?

**Pull request closed without merging**
