### PR TITLE
[Release] v0.4.0 - Upgrade to ZendeskChat V2

### PR DESCRIPTION
**Pull request by fbartho**
This pull-request is ready for testing!

- Fixes: #57 
- Fixes: #59

# Status

- [x] Partial Implementation for iOS - Crashes inside of Zendesk Swift Code :-( -- customer support notified
- [x] Implementation for iOS
- [x] Implementation for Android
- [x] Readme/Documentation Update
- [x] Migration Instructions

Our internal tracking ticket for this is https://taskrabbit.atlassian.net/browse/COREXP-1 (But this obviously won't help open source to read anything).

## Testing

If you're looking to test this Pull Request, you can do so by using this line in your `package.json dependencies`:
```json
"react-native-zendesk-chat": "taskrabbit/react-native-zendesk-chat#release/0.4.0",
```

Documentation is in the [Readme](https://github.com/taskrabbit/react-native-zendesk-chat/blob/50695eb0a7487e30f37354a76d21636fdf7de9eb/README.md)

As well as in the [TypeScript Types File](https://github.com/taskrabbit/react-native-zendesk-chat/blob/50695eb0a7487e30f37354a76d21636fdf7de9eb/RNZendeskChat.d.ts)

### CODE REVIEW

**Comment by samsonroymaben** [comment]
@fbartho 
When will this be released ? We have used this package in our project. Apple is rejecting the build.

**Comment by fbartho** [comment]
It’s not working yet.

## iOS
The iOS code here compiles and launches, but it crashes in my application inside Swift inside their library, so it appears I can’t debug the issue.
- I’ve sent an email to Zendesk Support to see if they can say what I did wrong.
- I could use more people testing this in their application (you can directly depend on this github branch if you want to try it out)

## Android
Not implemented yet.

---
In the github issues, I have a reference implementation from a 3rd party, that adapted this library for a client.

It provides many features that we won’t be carrying over (extra dependencies), but we might figure out what I missed by comparing that work.

I want to ship this as soon as possible, but I’m stuck!

**Comment by fbartho** [comment]
@samsonroymaben -- Got iOS working today. -- We'll see about Android this coming week.

**Comment by fbartho** [comment]
@samsonroymaben If you get a chance, please test this branch out! -- instructions included in the PR description.

I'd like to ship this this week.

**Comment by samsonroymaben** [comment]
@fbartho I have used this pod command -  
`pod 'RNZendeskChat', :git => 'https://github.com/taskrabbit/react-native-zendesk-chat.git'`
and this has still references to `ZDCChat` which has references of UIWebview. How do i resolve this ?

**Comment by fbartho** [comment]
@samsonroymaben -- my Podfile does not include RNZendeskChat.

If you're on RN 0.62, all you need to do is put this in your package.json
```json
"react-native-zendesk-chat": "taskrabbit/react-native-zendesk-chat#release/0.4.0",
```
Then you need to `yarn install` and `(cd ios; pod install)`

What you've put in your Podfile is a reference to the default branch (not to this PR's branch), so of course you won't see any changes.

If you read the Readme in this PR, you'll notice that we don't recommend you add anything to your Podfile as RN 0.62 auto-detects any Podfile dependencies if you have it configured properly.

**Comment by samsonroymaben** [comment]
> @samsonroymaben -- my Podfile does not include RNZendeskChat.
> 
> If you're on RN 0.62, all you need to do is put this in your package.json
> 
> ```json
> "react-native-zendesk-chat": "taskrabbit/react-native-zendesk-chat#release/0.4.0",
> ```
> 
> Then you need to `yarn install` and `(cd ios; pod install)`
> 
> What you've put in your Podfile is a reference to the default branch (not to this PR's branch), so of course you won't see any changes.
> 
> If you read the Readme in this PR, you'll notice that we don't recommend you add anything to your Podfile as RN 0.62 auto-detects any Podfile dependencies if you have it configured properly.

@fbartho I am currently using 0.59.9 version of react.

**Comment by fbartho** [comment]
@samsonroymaben You should still be able to test this branch with my advice above.

If you’re not using Cocoapods, you need to additionally use `react-native link` to get native Packages properly linked in.

I’m not currently set up with 0.59, but I believe it *should work*, I just cannot provide detailed support for that at this time.

In regards to this PR, I’ll try to see if my work QA can help. (But we don’t use every/many features)

---

Upgrading to 0.62 or later is definitely a (hard) thing you need to do, as 0.60 came out a year ago!

When 0.63 drops, I’ll consider dropping support for 0.59 in other libraries I maintain, as Cocoapods significantly changed/improved across 60/61/62

**Pull request merged**
