### PR TITLE
Updates to support Cocoapods for RN 0.62

### PR DESCRIPTION
**Pull request by robertmurray**
Added License file and podspec to support CocaPods for RN 0.62. Updated package.json.

### CODE REVIEW

**Comment by zanechua** [comment]
Do you not need to bump the `s.platform` to iOS 10.0 and above? The latest zendesk pods require you to use iOS 10.0 and above.

**Comment by fbartho** [comment]
Nice catch @zanechua do you see any other details we should catch? Before this, we weren’t using cocoapods in our main projects.

**Comment by zanechua** [comment]
Yes. There are actually a few changes that I've made to my own fork of this repo. Was just speaking to the authors that were listed inside the `package.json` about the changes to allow Podspecs via email.

In this PR I see that the docs were updated to require you to include the `RNZendeskChat` Pod and to import the header files directly into our projects but that shouldn't be necessary because of updates to RN0.6x and above.

I've made the changes in my repo and referenced them below. In my own react-native app, we do not have to add any code at all into the Podfile. We just add the `react-native-zendesk-chat` package and we're good to go for iOS.

https://github.com/zanechua/react-native-zendesk-chat/commit/117e224a25af87a800b8a1bd6066b533cd459cc0

**Comment by zanechua** [comment]
@robertmurray any reason why we're not using auto-linking and still requiring the manual import of the zendesk header files?

**Pull request merged**
